imagePullSecrets: []

secret:
  certs: orc8r-fluentd-tls

fluentd_daemon:
  create: false

  image:
    repository: "gcr.io/google-containers/fluentd-elasticsearch"
    tag: "v2.4.0"
    pullPolicy: IfNotPresent

  env:
    elastic_host: "elasticsearch-master"
    elastic_port: "9200"
    elastic_scheme: "http"

  resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

fluentd_forward:
  create: true

  # Domain-proxy output
  dp_output: true

  replicas: 1

  nodeSelector: {}
  tolerations: []
  affinity: {}

  image:
    repository: "gcr.io/google-containers/fluentd-elasticsearch"
    tag: "v2.4.0"
    pullPolicy: IfNotPresent

  # env:
  #   elastic_host: "elasticsearch-master"
  #   elastic_port: "9200"
  #   elastic_scheme: "http"
  #   elastic_flush_interval: 5s

  env:
    FLUENTD_CONF: "/etc/fluent/fluent.conf"
    FLUENT_ELASTICSEARCH_HOST: "elasticsearch-master"
    FLUENT_ELASTICSEARCH_PORT: "9200"
    FLUENT_ELASTICSEARCH_SCHEME: "http"
    FLUENT_ELASTICSEARCH_SSL_VERIFY: "false"
    FLUENT_ELASTICSEARCH_SSL_VERSION: "TLSv1"
    FLUENT_ELASTICSEARCH_RELOAD_CONNECTIONS: "false"
    FLUENT_ELASTICSEARCH_RECONNECT_ON_ERROR: "true"
    FLUENT_ELASTICSEARCH_RELOAD_ON_FAILURE: "true"
    FLUENT_ELASTICSEARCH_LOG_ES_400_REASON: "true"
    FLUENT_ELASTICSEARCH_DP_LOGSTASH_PREFIX: "dp"
    FLUENT_ELASTICSEARCH_LOGSTASH_FORMAT: "true"
    FLUENT_ELASTICSEARCH_LOGSTASH_DP_INDEX_NAME: "dp"
    FLUENT_ELASTICSEARCH_LOGSTASH_TYPE_NAME: "fluentd"
    FLUENT_ELASTICSEARCH_BUFFER_FLUSH_THREAD_COUNT: "8"
    FLUENT_ELASTICSEARCH_BUFFER_FLUSH_INTERVAL: "5s"
    FLUENT_ELASTICSEARCH_BUFFER_CHUNK_LIMIT_SIZE: "2M"
    FLUENT_ELASTICSEARCH_BUFFER_QUEUE_LIMIT_LENGTH: "32"
    FLUENT_ELASTICSEARCH_BUFFER_RETRY_MAX_INTERVAL: "30"

  resources: {}

  service:
    targetPort: 24224
    type: ClusterIP

elasticsearch-curator:
  create: false

  configMaps:
    config_yml: |-
      ---
      client:
        hosts:
          - CHANGEME.host
        port: 9200
        # url_prefix:
        # use_ssl: True
        # certificate:
        # client_cert:
        # client_key:
        # ssl_no_validate: True
        # http_auth:
        # timeout: 30
        # master_only: False
      # logging:
      #   loglevel: INFO
      #   logfile:
      #   logformat: default
      #   blacklist: ['elasticsearch', 'urllib3']
