version: 2
jobs:
  build:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: helm-charts
          environment:
            - GITHUB_PAGES_REPO: cristi0204/helm-charts
          command: wget -O - https://raw.githubusercontent.com/cristi0204/helm-charts/master/publish.sh | sh