
{{- if .Values.hpav2.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "apache-nifi.fullname" . }}-hpav2
  labels:
    app.kubernetes.io/name: {{ include "apache-nifi.name" . | quote }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ template "apache-nifi.fullname" . }}
  minReplicas: {{ .Values.hpav2.minReplicas }}
  maxReplicas: {{ .Values.hpav2.maxReplicas }}
  behavior:
    scaleUp:
      policies:
        - periodSeconds: 60
          type: Pods
          value: 1
#       selectPolicy: Max
      stabilizationWindowSeconds: {{ .Values.hpav2.stabilizationWindowSeconds }}
    scaleDown:
      policies:
        - periodSeconds: 60
          type: Pods
          value: 1
#       selectPolicy: Max
      stabilizationWindowSeconds: {{ .Values.hpav2.stabilizationWindowSeconds }}
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpav2.averageMemoryUtilization }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpav2.averageCpuUtilization }}
{{- end }}
