---
apiVersion: v2
name: nifi
version: 1.0.1
appVersion: 1.16.3
description: Apache NiFi is a software project from the Apache Software Foundation designed to automate the flow of data between software systems.

dependencies:
  - name: zookeeper
    version: 9.2.7
    repository: https://charts.bitnami.com/bitnami
    condition: zookeeper.enabled
  - name: nifi-registry
    alias: registry
    version: 1.0.0
    repository: https://dysnix.github.io/charts/
    condition: registry.enabled
  - name: ca
    version: 1.0.1
    condition: ca.enabled
  - name: openldap
    version: ~1.2.4
    repository: https://charts.helm.sh/stable
    condition: openldap.enabled
